spring.application.name=mymoney
server.port=8081
spring.thymeleaf.cache=true

# Set a context path
server.servlet.context-path=/mymoney

# Actuator configuration
management.endpoints.web.exposure.include=info,metrics,health,loggers,httpexchanges,scheduledtasks,integrationgraph
management.endpoint.health.show-details=always
management.info.build.enabled=false
management.info.env.enabled=true
management.info.git.enabled=true
management.info.git.mode=full

# info endpoint configuration
info.app.name=@project.name@
info.app.description=@project.description@
info.app.build.date=@maven.build.timestamp@
info.app.build.version=@project.version@
info.app.java.compiler.version=@java.version@